DEALS = [
  dict(n=1,addr="4415 Thompson Mill Rd",city="Buford",zp="30519",ac=43.52,zn="M1-Light Industry",
    lv=7502400,seller="DUKE REALTY LAND LLC (now Prologis)",sloc="Denver, CO",
    sph="(678) 249-7001 (Kent Mason, GA) | (303) 567-5000 (HQ)",sem="prologis.com/contact-us",
    held="Legacy parcels (Prologis acquired Duke 2022)",paid="Various",liens="None",
    b1n="Shaheen & Company",b1p="(770) 916-1775",b1e="info@shaheenco.com",
    b2n="Starwood Capital Group",b2p="(770) 541-9046",b2e="sfr_inquiries@starwood.com",
    ss="Hi, I'm calling for Kent Mason or the Georgia market team at Prologis. My name is [YOUR NAME], I'm a commercial land investor.\n\nI'm reaching out about several Duke Realty legacy parcels on Thompson Mill Road in Buford — totaling 43 acres of M1-zoned industrial land across 5 contiguous parcels. Since Prologis absorbed Duke in 2022, I imagine there's been a portfolio review and these may be non-core assets.\n\n43 acres of undeveloped land generating zero revenue is a drag on the balance sheet. I have institutional buyers ready to close on industrial land in the I-985 corridor. I'd like to discuss a package deal. Can we set up a call with whoever handles dispositions?",
    bs="I've secured 43 acres of M1-zoned industrial land on Thompson Mill Rd in Buford — 5 contiguous parcels from Prologis's Duke Realty legacy portfolio. Shaheen already holds $74.9M in industrial assets in Gwinnett.\n\nAt $5.25M for the package, that's $120K/acre for entitled industrial in the I-985 corridor. Motivated institutional seller. Clean title.",
    lev="Prologis absorbed Duke 2022 — legacy land review. 43 acres producing zero income. Package deal = one close."),

  dict(n=2,addr="2900 Rolling Pin Ln",city="Suwanee",zp="30024",ac=15.69,zn="M1-Light Industry",
    lv=2500000,seller="SCHWANS BAKERY OPERATIONS LLC",sloc="Marshall, MN",
    sph="(800) 533-5290 (Corporate) | (888) 554-7421 (Foodservice)",sem="schwanscompany.com/contact",
    held="Unknown (CJ CheilJedang acquired Schwan's 2019)",paid="N/A",liens="None",
    b1n="Prologis — Kent Mason",b1p="(678) 249-7001",b1e="prologis.com/contact-us",
    b2n="Shaheen & Company",b2p="(770) 916-1775",b2e="info@shaheenco.com",
    ss="Hi, I'm calling Schwan's corporate regarding a real estate matter. I'm [YOUR NAME], a commercial land investor in the Atlanta area.\n\nI'm reaching out about a 15.7-acre M1-zoned parcel at 2900 Rolling Pin Lane in Suwanee, Georgia. Since CJ CheilJedang's acquisition, I understand there's been operational consolidation. If this site isn't part of the go-forward plan, I'd like to discuss a cash purchase.\n\nCould you connect me with corporate real estate or property disposition?",
    bs="I've locked up 15.7 acres of M1 industrial on Rolling Pin Lane in Suwanee — the Peachtree Industrial corridor. Prologis already has a major presence along I-985.\n\nFood company consolidating post-acquisition. Motivated to divest non-core assets. I can deliver well below market.",
    lev="Korean conglomerate acquired Schwan's 2019 — consolidating operations. Non-core GA real estate."),

  dict(n=3,addr="Windsor Park Dr",city="Suwanee",zp="30024",ac=12.09,zn="M1-Light Industry",
    lv=1689200,seller="SOUTHEASTERN FREIGHT LINES INC",sloc="Lexington, SC",
    sph="(803) 794-7300 (HQ) | (800) 637-7335 (Toll-Free)",sem="sefl.com/contact",
    held="Long-term hold",paid="N/A",liens="None",
    b1n="Prologis — Kent Mason",b1p="(678) 249-7001",b1e="prologis.com/contact-us",
    b2n="Shaheen & Company",b2p="(770) 916-1775",b2e="info@shaheenco.com",
    ss="Hi, I'm calling about a property matter for Southeastern Freight Lines. I'm [YOUR NAME], a land investor in Gwinnett County.\n\nYou have two adjacent vacant parcels on Windsor Park Drive in Suwanee totaling 12 acres — both M1-zoned. I understand freight companies periodically review their real estate footprint. If these aren't part of active terminal plans, I'd like to make a cash offer for both parcels as a package.\n\nCould you connect me with whoever handles property disposition or surplus real estate?",
    bs="12 acres of contiguous M1 industrial on Windsor Park Dr in Suwanee — freight company divesting surplus land. Two parcels, clean title, no liens. Package deal at $1.18M.",
    lev="Trucking companies regularly divest surplus parcels. 12 acres vacant = not part of terminal plans."),

  dict(n=4,addr="2172 Lawrenceville Suwanee Rd",city="Suwanee",zp="30024",ac=7.31,zn="C2-General Business",
    lv=4407500,seller="LIDL US OPERATIONS LLC",sloc="Arlington, VA",
    sph="(703) 214-3433 (Real Estate Dept)",sem="realestate@lidl.us",
    held="Recent acquisition",paid="N/A",liens="None",
    b1n="AOA Parish Real Estate Trust",b1p="(404) 920-7800",b1e="Via certified letter",
    b2n="Shaheen & Company",b2p="(770) 916-1775",b2e="info@shaheenco.com",
    ss="Hi, I'm calling Lidl's real estate department. My name is [YOUR NAME], I'm a commercial land investor in the Suwanee, Georgia market.\n\nI'm reaching out about two C2-zoned parcels Lidl holds in Gwinnett County — 4.67 acres on Lawrenceville Suwanee Road and 2.64 acres on Nelson Brogdon Road in Buford. Combined that's 7.3 acres of prime commercial land.\n\nIf Lidl has decided not to develop these sites, I have commercial buyers ready to close quickly. I'd like to discuss a purchase. Can I also email details to realestate@lidl.us?",
    bs="7.3 acres of C2 commercial across two Gwinnett parcels — Suwanee and Buford. Lidl acquired for store development but sites are still vacant. I can deliver at 30% below assessed. AOA Parish holds $59.6M in commercial across Gwinnett.",
    lev="Lidl has dedicated RE dept and email. They acquire aggressively, sometimes drop sites. $4.4M value."),

  dict(n=5,addr="Hwy 316",city="Dacula",zp="30019",ac=10.01,zn="M1-Light Industry",
    lv=500000,seller="CSX TRANSPORTATION INC",sloc="Jacksonville, FL",
    sph="(877) 835-8279 (Real Property) | (904) 359-3200 (HQ)",sem="csx.com/contact",
    held="36 years (since 12/18/1989)",paid="$451,200",liens="None",
    b1n="Prologis — Kent Mason",b1p="(678) 249-7001",b1e="prologis.com/contact-us",
    b2n="Shaheen & Company",b2p="(770) 916-1775",b2e="info@shaheenco.com",
    ss="Hi, I'm calling CSX's Real Property department. My name is [YOUR NAME], I'm a land investor in Gwinnett County, Georgia.\n\nI'm interested in a 10-acre M1-zoned parcel on Highway 316 in Dacula — it's been in CSX's portfolio since December 1989. That's 36 years of carrying a vacant lot that doesn't appear to be part of any active rail operations.\n\nThe Hwy 316 corridor is booming with development. I have industrial buyers ready to close. I'd like to submit a formal offer through your disposition process.",
    bs="10 acres M1-zoned on Hwy 316 in Dacula — the hottest growth corridor in East Gwinnett. Railroad surplus land, held 36 years, clean title. At $350K, that's $35K/acre for entitled industrial on a major highway.",
    lev="36 YEARS held. Railroad surplus. CSX has dedicated Real Property dept — call (877) 835-8279."),

  dict(n=6,addr="Best Friend Rd",city="Doraville",zp="30340",ac=4.31,zn="M1-Light Industry",
    lv=598100,seller="ROLLINS LEASING CORP (now Penske Truck Leasing)",sloc="Reading, PA",
    sph="(855) 345-7268 (Penske Corporate)",sem="pensketruckleasing.com/contact",
    held="Legacy asset (Penske acquired Rollins)",paid="N/A",liens="None",
    b1n="Shaheen & Company",b1p="(770) 916-1775",b1e="info@shaheenco.com",
    b2n="Prologis — Kent Mason",b2p="(678) 249-7001",b2e="prologis.com/contact-us",
    ss="Hi, I'm calling Penske regarding a legacy property from the Rollins Leasing acquisition. I'm [YOUR NAME], a land investor in Metro Atlanta.\n\nThere's a 4.3-acre M1-zoned parcel on Best Friend Road in Doraville still titled under Rollins Leasing Corp. With the Doraville/Assembly corridor booming, this asset has appreciated significantly. Rather than continuing to carry it, I'd like to discuss a cash purchase.\n\nCould you direct me to whoever handles legacy real estate disposition?",
    bs="4.3 acres M1-zoned on Best Friend Rd in Doraville — the Assembly/Porsche corridor. Legacy Penske/Rollins asset. Clean title, $598K value. I can deliver at $418K.",
    lev="Penske absorbed Rollins — orphaned corporate land. Doraville is booming with Assembly development."),

  dict(n=7,addr="Turman Dr",city="Berkeley Lake",zp="30071",ac=2.97,zn="R100-Single Family",
    lv=246300,seller="JOSEPH T RYERSON & SONS INC (NYSE: RYI)",sloc="Chicago, IL",
    sph="(312) 292-5000 (HQ) | (855) 793-7766 (Customer)",sem="ryerson.com/contact",
    held="Long-term hold",paid="N/A",liens="None",
    b1n="Invitation Homes",b1p="(770) 442-3372",b1e="invitationhomes.com/contact-us",
    b2n="Starwood Capital Group",b2p="(770) 541-9046",b2e="sfr_inquiries@starwood.com",
    ss="Hi, I'm calling Ryerson's corporate office. I'm [YOUR NAME], a residential land investor in Metro Atlanta.\n\nRyerson holds a 3-acre R100-zoned residential parcel on Turman Drive in Berkeley Lake, Georgia. As a steel distribution company, this clearly isn't a core asset. I'd like to make a cash offer that gets this off your books.\n\nCould you connect me with corporate real estate or whoever handles non-core property disposition?",
    bs="3 acres R100 residential in Berkeley Lake — one of the most exclusive communities in Gwinnett. NYSE steel company divesting non-core land. Premium location, clean title. I can deliver at $172K.",
    lev="NYSE steel company holding residential land. 100% non-core. Any offer is cleanup for them."),

  dict(n=8,addr="Hwy 20",city="Loganville",zp="30052",ac=6.66,zn="M1-Light Industry",
    lv=45700,seller="COPART OF CONNECTICUT INC (NASDAQ: CPRT)",sloc="Dallas, TX",
    sph="(972) 868-4400 (Corporate)",sem="copart.com/contact",
    held="4 years (since 07/2022)",paid="$295,000",liens="None",
    b1n="Shaheen & Company",b1p="(770) 916-1775",b1e="info@shaheenco.com",
    b2n="Prologis — Kent Mason",b2p="(678) 249-7001",b2e="prologis.com/contact-us",
    ss="Hi, I'm calling Copart corporate about a property in Georgia. I'm [YOUR NAME], a land investor in the Loganville area.\n\nCopart holds a 6.7-acre M1-zoned parcel on Highway 20 in Loganville — purchased in July 2022 for $295,000. If this site isn't being developed for auto auction operations, I have industrial buyers ready to close.\n\nCould you connect me with real estate or property disposition?",
    bs="6.7 acres M1-zoned on Hwy 20 in Loganville — the next growth frontier in East Metro Atlanta. Auto auction company surplus. Paid $295K, I can deliver at $206K below that basis.",
    lev="NASDAQ auto auction company. Paid $295K. If not building a yard, it's surplus."),

  dict(n=9,addr="3145 Willow Glade Trl",city="Lawrenceville",zp="30043",ac=6.62,zn="R100-Single Family",
    lv=347800,seller="STANLEY MARTIN COMPANIES LLC (Daiwa House)",sloc="Reston, VA",
    sph="(703) 621-2050 (Corporate HQ)",sem="stanleymartin.com/contact",
    held="3 years (since 01/2023)",paid="N/A",liens="None",
    b1n="Invitation Homes",b1p="(770) 442-3372",b1e="invitationhomes.com/contact-us",
    b2n="Starwood Capital Group",b2p="(770) 541-9046",b2e="sfr_inquiries@starwood.com",
    ss="Hi, I'm calling Stanley Martin's land acquisitions team. I'm [YOUR NAME], a residential land investor in Gwinnett County.\n\nStanley Martin holds a 6.6-acre R100 parcel on Willow Glade Trail in Lawrenceville — acquired in January 2023. If this site didn't make the cut for your build pipeline, I'd like to discuss purchasing it. I have SFR buyers actively looking for entitled residential land in Lawrenceville.\n\nWho handles surplus land or lot dispositions in your Georgia division?",
    bs="6.6 acres R100 in Lawrenceville — national builder surplus. Stanley Martin acquired in 2023 but hasn't developed. Clean, entitled residential land at $243K. 5-6 luxury lot potential.",
    lev="National builder (Daiwa House). If not in their pipeline after 3 years, it's surplus."),

  dict(n=10,addr="5380 Cole Rd",city="Buford",zp="30518",ac=9.73,zn="C2-General Business",
    lv=3204200,seller="AMERCO REAL ESTATE CO (U-Haul parent)",sloc="Phoenix, AZ",
    sph="(602) 263-6645 (AMERCO Corporate)",sem="amerco.com",
    held="2 years (since 03/2024)",paid="$3,500,000",liens="None",
    b1n="AOA Parish Real Estate Trust",b1p="(404) 920-7800",b1e="Via certified letter",
    b2n="Shaheen & Company",b2p="(770) 916-1775",b2e="info@shaheenco.com",
    ss="Hi, I'm calling AMERCO's real estate division. I'm [YOUR NAME], a commercial land investor in Buford, Georgia.\n\nAMERCO acquired a 9.7-acre C2-zoned parcel on Cole Road in Buford in March 2024 for $3.5 million. If U-Haul's development plans for this site have changed, I have commercial buyers who can close quickly on C2 land in the Buford corridor.\n\nCould you connect me with whoever manages site dispositions?",
    bs="9.7 acres C2 commercial on Cole Rd in Buford. U-Haul parent paid $3.5M in 2024 but site is undeveloped. AOA Parish holds $59.6M in commercial properties across Gwinnett. I can deliver at $2.24M — 36% below acquisition.",
    lev="U-Haul parent paid $3.5M recently. If plans changed, they want capital back fast."),

  dict(n=11,addr="302 Satellite Blvd",city="Suwanee",zp="30024",ac=20.28,zn="M1-Light Industry",
    lv=3000000,seller="VENTURE REAL ESTATE INVESTMENT GROUP LLC",sloc="Albany, NY",
    sph="(518) 456-3600 (Albany office)",sem="Mail: 1971 Western Ave Ste 1122, Albany NY 12203",
    held="Unknown",paid="N/A",liens="None",
    b1n="Prologis — Kent Mason",b1p="(678) 249-7001",b1e="prologis.com/contact-us",
    b2n="Shaheen & Company",b2p="(770) 916-1775",b2e="info@shaheenco.com",
    ss="Hi, I'm trying to reach Venture Real Estate Investment Group. I'm [YOUR NAME], a land investor in Gwinnett County, Georgia.\n\nVenture holds a 20-acre M1-zoned parcel on Satellite Boulevard in Suwanee. That's prime logistics corridor real estate. If the group is looking for an exit on this asset, I have institutional industrial buyers who can close quickly.\n\nIs there a principal or managing member I can speak with about a purchase?",
    bs="20 acres M1-zoned on Satellite Blvd in Suwanee — prime logistics location. NY investment group looking for exit. I can deliver at $2.1M for 20 acres of entitled industrial.",
    lev="NY investment group. 20 acres producing zero income. Satellite Blvd = top logistics corridor."),

  dict(n=12,addr="1000 Sugarmont Pass",city="Lawrenceville",zp="30044",ac=74.52,zn="M1-Light Industry",
    lv=12547500,seller="FF PIX 5030 SUGARLOAF LLC (Attn: Jeffrey Theobald)",sloc="Boston, MA",
    sph="GA SOS registered agent lookup required",sem="Mail: Attn Jeffrey Theobald, Boston MA 02110",
    held="Unknown",paid="N/A",liens="None",
    b1n="Prologis — Kent Mason",b1p="(678) 249-7001",b1e="prologis.com/contact-us",
    b2n="Starwood Capital Group",b2p="(770) 541-9046",b2e="sfr_inquiries@starwood.com",
    ss="Dear Mr. Theobald,\n\nI'm writing regarding FF Pix 5030 Sugarloaf LLC's 74.5-acre M1-zoned parcel at 1000 Sugarmont Pass in Lawrenceville, Georgia. This is one of the largest undeveloped industrial tracts in Gwinnett County.\n\nI represent institutional buyers actively seeking large-scale industrial development sites in the I-85 corridor. I'd like to discuss a potential acquisition. Please contact me at [YOUR PHONE] or [YOUR EMAIL] at your earliest convenience.",
    bs="74.5 acres of M1 industrial at Sugarmont Pass, Lawrenceville — one of the largest undeveloped tracts in Gwinnett. $12.5M assessed value. Boston investment fund. Whale deal — I can deliver at $8.7M.",
    lev="WHALE DEAL. 74.5 acres. $12.5M. Boston fund. Send certified letter to Jeffrey Theobald."),

  dict(n=13,addr="Richland Creek",city="Buford",zp="30518",ac=8.3,zn="M1-Light Industry",
    lv=1610800,seller="NWC #6 LLC",sloc="Puyallup, WA",
    sph="Mail: PO Box 73399, Puyallup WA 98373",sem="WA SOS registered agent lookup",
    held="7 months (since 10/2025)",paid="$2,156,000",liens="None",
    b1n="Shaheen & Company",b1p="(770) 916-1775",b1e="info@shaheenco.com",
    b2n="Prologis — Kent Mason",b2p="(678) 249-7001",b2e="prologis.com/contact-us",
    ss="Hi, I'm trying to reach the managing member of NWC #6 LLC. I'm [YOUR NAME], a land investor in Buford, Georgia.\n\nNWC #6 acquired 8.3 acres of M1 land on Richland Creek in Buford last October for $2.15 million. If your development timeline has shifted or you're looking for a quick return, I have industrial buyers who can close in 30 days.\n\nI'd love to discuss numbers. Please call me at [YOUR PHONE].",
    bs="8.3 acres M1-zoned on Richland Creek, Buford. Recent acquisition at $2.15M — WA LLC may flip. I can deliver at $1.5M.",
    lev="Paid $2.15M just 7 months ago. If plans changed = quick flip potential."),

  dict(n=14,addr="1750 Pirkle Rd",city="Norcross",zp="30093",ac=7.78,zn="RM-Multi-family",
    lv=157400,seller="MASONRY BRICKS AND DEVELOPMENT CORP",sloc="Miami, FL",
    sph="Mail: 19800 SW 180th Ave Lot 511, Miami FL 33187",sem="FL SOS registered agent lookup",
    held="3 years (since 03/2023)",paid="$16,591",liens="None",
    b1n="Invitation Homes",b1p="(770) 442-3372",b1e="invitationhomes.com/contact-us",
    b2n="Starwood Capital Group",b2p="(770) 541-9046",b2e="sfr_inquiries@starwood.com",
    ss="Hi, I'm trying to reach the principal of Masonry Bricks and Development. I'm [YOUR NAME], a land investor in Gwinnett County.\n\nYou acquired 7.8 acres of RM-zoned land on Pirkle Road in Norcross in 2023 for $16,591. That's multi-family entitled land now assessed at $157,000. If you're looking for a development partner or a quick sale, I have multi-family buyers who can close fast.\n\nPlease call me at [YOUR PHONE].",
    bs="7.8 acres RM multi-family zoned on Pirkle Rd, Norcross. Miami developer paid $16.6K — now worth $157K. Apartment or townhouse play. I can deliver at $110K.",
    lev="Paid $16.6K, worth $157K. Miami developer may need JV partner or quick exit."),

  dict(n=15,addr="Lebanon Rd",city="Lawrenceville",zp="30043",ac=9.43,zn="R100-Single Family",
    lv=1000,seller="LEBANON ROAD LAWRENCEVILLE LP",sloc="Calabasas, CA",
    sph="Mail: 23975 Park Sorrento Ste 220, Calabasas CA 91302",sem="CA SOS registered agent lookup",
    held="2 years (since 07/2024)",paid="$0",liens="None",
    b1n="Invitation Homes",b1p="(770) 442-3372",b1e="invitationhomes.com/contact-us",
    b2n="Starwood Capital Group",b2p="(770) 541-9046",b2e="sfr_inquiries@starwood.com",
    ss="Hi, I'm trying to reach the managing partner of Lebanon Road Lawrenceville LP. I'm [YOUR NAME], a residential land investor in Gwinnett County, Georgia.\n\nYour LP holds 9.4 acres of R100-zoned land on Lebanon Road in Lawrenceville — acquired July 2024. If the fund is looking for an exit or the development timeline has changed, I have SFR buyers actively acquiring residential land in Lawrenceville right now.\n\nI'd appreciate a callback at [YOUR PHONE].",
    bs="9.4 acres R100 residential on Lebanon Rd, Lawrenceville. Calabasas investment LP. Clean title, $1K assessed — likely recently rezoned or transferred. 7-8 lot subdivision potential.",
    lev="Calabasas CA investment LP. Entertainment money may want quick returns."),
]
