export const deals = [
  {
    "n": 1,
    "addr": "4415 Thompson Mill Rd",
    "city": "Buford",
    "zp": "30519",
    "ac": 43.52,
    "zn": "M1-Light Industry",
    "lv": 7502400,
    "seller": "DUKE REALTY LAND LLC (now Prologis)",
    "sloc": "Denver, CO",
    "sph": "(678) 249-7001 (Kent Mason, GA) | (303) 567-5000 (HQ)",
    "sem": "prologis.com/contact-us",
    "held": "Legacy parcels (Prologis acquired Duke 2022)",
    "paid": "Various",
    "liens": "None",
    "b1n": "Shaheen & Company",
    "b1p": "(770) 916-1775",
    "b1e": "info@shaheenco.com",
    "b2n": "Starwood Capital Group",
    "b2p": "(770) 541-9046",
    "b2e": "sfr_inquiries@starwood.com",
    "ss": "Hi, I'm calling for Kent Mason or the Georgia market team at Prologis. My name is [YOUR NAME], I'm a commercial land investor.\n\nI'm reaching out about several Duke Realty legacy parcels on Thompson Mill Road in Buford \u2014 totaling 43 acres of M1-zoned industrial land across 5 contiguous parcels. Since Prologis absorbed Duke in 2022, I imagine there's been a portfolio review and these may be non-core assets.\n\n43 acres of undeveloped land generating zero revenue is a drag on the balance sheet. I have institutional buyers ready to close on industrial land in the I-985 corridor. I'd like to discuss a package deal. Can we set up a call with whoever handles dispositions?",
    "bs": "I've secured 43 acres of M1-zoned industrial land on Thompson Mill Rd in Buford \u2014 5 contiguous parcels from Prologis's Duke Realty legacy portfolio. Shaheen already holds $74.9M in industrial assets in Gwinnett.\n\nAt $5.25M for the package, that's $120K/acre for entitled industrial in the I-985 corridor. Motivated institutional seller. Clean title.",
    "lev": "Prologis absorbed Duke 2022 \u2014 legacy land review. 43 acres producing zero income. Package deal = one close."
  },
  {
    "n": 2,
    "addr": "2900 Rolling Pin Ln",
    "city": "Suwanee",
    "zp": "30024",
    "ac": 15.69,
    "zn": "M1-Light Industry",
    "lv": 2500000,
    "seller": "SCHWANS BAKERY OPERATIONS LLC",
    "sloc": "Marshall, MN",
    "sph": "(800) 533-5290 (Corporate) | (888) 554-7421 (Foodservice)",
    "sem": "schwanscompany.com/contact",
    "held": "Unknown (CJ CheilJedang acquired Schwan's 2019)",
    "paid": "N/A",
    "liens": "None",
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(678) 249-7001",
    "b1e": "prologis.com/contact-us",
    "b2n": "Shaheen & Company",
    "b2p": "(770) 916-1775",
    "b2e": "info@shaheenco.com",
    "ss": "Hi, I'm calling Schwan's corporate regarding a real estate matter. I'm [YOUR NAME], a commercial land investor in the Atlanta area.\n\nI'm reaching out about a 15.7-acre M1-zoned parcel at 2900 Rolling Pin Lane in Suwanee, Georgia. Since CJ CheilJedang's acquisition, I understand there's been operational consolidation. If this site isn't part of the go-forward plan, I'd like to discuss a cash purchase.\n\nCould you connect me with corporate real estate or property disposition?",
    "bs": "I've locked up 15.7 acres of M1 industrial on Rolling Pin Lane in Suwanee \u2014 the Peachtree Industrial corridor. Prologis already has a major presence along I-985.\n\nFood company consolidating post-acquisition. Motivated to divest non-core assets. I can deliver well below market.",
    "lev": "Korean conglomerate acquired Schwan's 2019 \u2014 consolidating operations. Non-core GA real estate."
  },
  {
    "n": 3,
    "addr": "Windsor Park Dr",
    "city": "Suwanee",
    "zp": "30024",
    "ac": 12.09,
    "zn": "M1-Light Industry",
    "lv": 1689200,
    "seller": "SOUTHEASTERN FREIGHT LINES INC",
    "sloc": "Lexington, SC",
    "sph": "(803) 794-7300 (HQ) | (800) 637-7335 (Toll-Free)",
    "sem": "sefl.com/contact",
    "held": "Long-term hold",
    "paid": "N/A",
    "liens": "None",
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(678) 249-7001",
    "b1e": "prologis.com/contact-us",
    "b2n": "Shaheen & Company",
    "b2p": "(770) 916-1775",
    "b2e": "info@shaheenco.com",
    "ss": "Hi, I'm calling about a property matter for Southeastern Freight Lines. I'm [YOUR NAME], a land investor in Gwinnett County.\n\nYou have two adjacent vacant parcels on Windsor Park Drive in Suwanee totaling 12 acres \u2014 both M1-zoned. I understand freight companies periodically review their real estate footprint. If these aren't part of active terminal plans, I'd like to make a cash offer for both parcels as a package.\n\nCould you connect me with whoever handles property disposition or surplus real estate?",
    "bs": "12 acres of contiguous M1 industrial on Windsor Park Dr in Suwanee \u2014 freight company divesting surplus land. Two parcels, clean title, no liens. Package deal at $1.18M.",
    "lev": "Trucking companies regularly divest surplus parcels. 12 acres vacant = not part of terminal plans."
  },
  {
    "n": 4,
    "addr": "2172 Lawrenceville Suwanee Rd",
    "city": "Suwanee",
    "zp": "30024",
    "ac": 7.31,
    "zn": "C2-General Business",
    "lv": 4407500,
    "seller": "LIDL US OPERATIONS LLC",
    "sloc": "Arlington, VA",
    "sph": "(703) 214-3433 (Real Estate Dept)",
    "sem": "realestate@lidl.us",
    "held": "Recent acquisition",
    "paid": "N/A",
    "liens": "None",
    "b1n": "AOA Parish Real Estate Trust",
    "b1p": "(404) 920-7800",
    "b1e": "Via certified letter",
    "b2n": "Shaheen & Company",
    "b2p": "(770) 916-1775",
    "b2e": "info@shaheenco.com",
    "ss": "Hi, I'm calling Lidl's real estate department. My name is [YOUR NAME], I'm a commercial land investor in the Suwanee, Georgia market.\n\nI'm reaching out about two C2-zoned parcels Lidl holds in Gwinnett County \u2014 4.67 acres on Lawrenceville Suwanee Road and 2.64 acres on Nelson Brogdon Road in Buford. Combined that's 7.3 acres of prime commercial land.\n\nIf Lidl has decided not to develop these sites, I have commercial buyers ready to close quickly. I'd like to discuss a purchase. Can I also email details to realestate@lidl.us?",
    "bs": "7.3 acres of C2 commercial across two Gwinnett parcels \u2014 Suwanee and Buford. Lidl acquired for store development but sites are still vacant. I can deliver at 30% below assessed. AOA Parish holds $59.6M in commercial across Gwinnett.",
    "lev": "Lidl has dedicated RE dept and email. They acquire aggressively, sometimes drop sites. $4.4M value."
  },
  {
    "n": 5,
    "addr": "Hwy 316",
    "city": "Dacula",
    "zp": "30019",
    "ac": 10.01,
    "zn": "M1-Light Industry",
    "lv": 500000,
    "seller": "CSX TRANSPORTATION INC",
    "sloc": "Jacksonville, FL",
    "sph": "(877) 835-8279 (Real Property) | (904) 359-3200 (HQ)",
    "sem": "csx.com/contact",
    "held": "36 years (since 12/18/1989)",
    "paid": "$451,200",
    "liens": "None",
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(678) 249-7001",
    "b1e": "prologis.com/contact-us",
    "b2n": "Shaheen & Company",
    "b2p": "(770) 916-1775",
    "b2e": "info@shaheenco.com",
    "ss": "Hi, I'm calling CSX's Real Property department. My name is [YOUR NAME], I'm a land investor in Gwinnett County, Georgia.\n\nI'm interested in a 10-acre M1-zoned parcel on Highway 316 in Dacula \u2014 it's been in CSX's portfolio since December 1989. That's 36 years of carrying a vacant lot that doesn't appear to be part of any active rail operations.\n\nThe Hwy 316 corridor is booming with development. I have industrial buyers ready to close. I'd like to submit a formal offer through your disposition process.",
    "bs": "10 acres M1-zoned on Hwy 316 in Dacula \u2014 the hottest growth corridor in East Gwinnett. Railroad surplus land, held 36 years, clean title. At $350K, that's $35K/acre for entitled industrial on a major highway.",
    "lev": "36 YEARS held. Railroad surplus. CSX has dedicated Real Property dept \u2014 call (877) 835-8279."
  },
  {
    "n": 6,
    "addr": "Best Friend Rd",
    "city": "Doraville",
    "zp": "30340",
    "ac": 4.31,
    "zn": "M1-Light Industry",
    "lv": 598100,
    "seller": "ROLLINS LEASING CORP (now Penske Truck Leasing)",
    "sloc": "Reading, PA",
    "sph": "(855) 345-7268 (Penske Corporate)",
    "sem": "pensketruckleasing.com/contact",
    "held": "Legacy asset (Penske acquired Rollins)",
    "paid": "N/A",
    "liens": "None",
    "b1n": "Shaheen & Company",
    "b1p": "(770) 916-1775",
    "b1e": "info@shaheenco.com",
    "b2n": "Prologis \u2014 Kent Mason",
    "b2p": "(678) 249-7001",
    "b2e": "prologis.com/contact-us",
    "ss": "Hi, I'm calling Penske regarding a legacy property from the Rollins Leasing acquisition. I'm [YOUR NAME], a land investor in Metro Atlanta.\n\nThere's a 4.3-acre M1-zoned parcel on Best Friend Road in Doraville still titled under Rollins Leasing Corp. With the Doraville/Assembly corridor booming, this asset has appreciated significantly. Rather than continuing to carry it, I'd like to discuss a cash purchase.\n\nCould you direct me to whoever handles legacy real estate disposition?",
    "bs": "4.3 acres M1-zoned on Best Friend Rd in Doraville \u2014 the Assembly/Porsche corridor. Legacy Penske/Rollins asset. Clean title, $598K value. I can deliver at $418K.",
    "lev": "Penske absorbed Rollins \u2014 orphaned corporate land. Doraville is booming with Assembly development."
  },
  {
    "n": 7,
    "addr": "Turman Dr",
    "city": "Berkeley Lake",
    "zp": "30071",
    "ac": 2.97,
    "zn": "R100-Single Family",
    "lv": 246300,
    "seller": "JOSEPH T RYERSON & SONS INC (NYSE: RYI)",
    "sloc": "Chicago, IL",
    "sph": "(312) 292-5000 (HQ) | (855) 793-7766 (Customer)",
    "sem": "ryerson.com/contact",
    "held": "Long-term hold",
    "paid": "N/A",
    "liens": "None",
    "b1n": "Invitation Homes",
    "b1p": "(770) 442-3372",
    "b1e": "invitationhomes.com/contact-us",
    "b2n": "Starwood Capital Group",
    "b2p": "(770) 541-9046",
    "b2e": "sfr_inquiries@starwood.com",
    "ss": "Hi, I'm calling Ryerson's corporate office. I'm [YOUR NAME], a residential land investor in Metro Atlanta.\n\nRyerson holds a 3-acre R100-zoned residential parcel on Turman Drive in Berkeley Lake, Georgia. As a steel distribution company, this clearly isn't a core asset. I'd like to make a cash offer that gets this off your books.\n\nCould you connect me with corporate real estate or whoever handles non-core property disposition?",
    "bs": "3 acres R100 residential in Berkeley Lake \u2014 one of the most exclusive communities in Gwinnett. NYSE steel company divesting non-core land. Premium location, clean title. I can deliver at $172K.",
    "lev": "NYSE steel company holding residential land. 100% non-core. Any offer is cleanup for them."
  },
  {
    "n": 8,
    "addr": "Hwy 20",
    "city": "Loganville",
    "zp": "30052",
    "ac": 6.66,
    "zn": "M1-Light Industry",
    "lv": 45700,
    "seller": "COPART OF CONNECTICUT INC (NASDAQ: CPRT)",
    "sloc": "Dallas, TX",
    "sph": "(972) 868-4400 (Corporate)",
    "sem": "copart.com/contact",
    "held": "4 years (since 07/2022)",
    "paid": "$295,000",
    "liens": "None",
    "b1n": "Shaheen & Company",
    "b1p": "(770) 916-1775",
    "b1e": "info@shaheenco.com",
    "b2n": "Prologis \u2014 Kent Mason",
    "b2p": "(678) 249-7001",
    "b2e": "prologis.com/contact-us",
    "ss": "Hi, I'm calling Copart corporate about a property in Georgia. I'm [YOUR NAME], a land investor in the Loganville area.\n\nCopart holds a 6.7-acre M1-zoned parcel on Highway 20 in Loganville \u2014 purchased in July 2022 for $295,000. If this site isn't being developed for auto auction operations, I have industrial buyers ready to close.\n\nCould you connect me with real estate or property disposition?",
    "bs": "6.7 acres M1-zoned on Hwy 20 in Loganville \u2014 the next growth frontier in East Metro Atlanta. Auto auction company surplus. Paid $295K, I can deliver at $206K below that basis.",
    "lev": "NASDAQ auto auction company. Paid $295K. If not building a yard, it's surplus."
  },
  {
    "n": 9,
    "addr": "3145 Willow Glade Trl",
    "city": "Lawrenceville",
    "zp": "30043",
    "ac": 6.62,
    "zn": "R100-Single Family",
    "lv": 347800,
    "seller": "STANLEY MARTIN COMPANIES LLC (Daiwa House)",
    "sloc": "Reston, VA",
    "sph": "(703) 621-2050 (Corporate HQ)",
    "sem": "stanleymartin.com/contact",
    "held": "3 years (since 01/2023)",
    "paid": "N/A",
    "liens": "None",
    "b1n": "Invitation Homes",
    "b1p": "(770) 442-3372",
    "b1e": "invitationhomes.com/contact-us",
    "b2n": "Starwood Capital Group",
    "b2p": "(770) 541-9046",
    "b2e": "sfr_inquiries@starwood.com",
    "ss": "Hi, I'm calling Stanley Martin's land acquisitions team. I'm [YOUR NAME], a residential land investor in Gwinnett County.\n\nStanley Martin holds a 6.6-acre R100 parcel on Willow Glade Trail in Lawrenceville \u2014 acquired in January 2023. If this site didn't make the cut for your build pipeline, I'd like to discuss purchasing it. I have SFR buyers actively looking for entitled residential land in Lawrenceville.\n\nWho handles surplus land or lot dispositions in your Georgia division?",
    "bs": "6.6 acres R100 in Lawrenceville \u2014 national builder surplus. Stanley Martin acquired in 2023 but hasn't developed. Clean, entitled residential land at $243K. 5-6 luxury lot potential.",
    "lev": "National builder (Daiwa House). If not in their pipeline after 3 years, it's surplus."
  },
  {
    "n": 10,
    "addr": "5380 Cole Rd",
    "city": "Buford",
    "zp": "30518",
    "ac": 9.73,
    "zn": "C2-General Business",
    "lv": 3204200,
    "seller": "AMERCO REAL ESTATE CO (U-Haul parent)",
    "sloc": "Phoenix, AZ",
    "sph": "(602) 263-6645 (AMERCO Corporate)",
    "sem": "amerco.com",
    "held": "2 years (since 03/2024)",
    "paid": "$3,500,000",
    "liens": "None",
    "b1n": "AOA Parish Real Estate Trust",
    "b1p": "(404) 920-7800",
    "b1e": "Via certified letter",
    "b2n": "Shaheen & Company",
    "b2p": "(770) 916-1775",
    "b2e": "info@shaheenco.com",
    "ss": "Hi, I'm calling AMERCO's real estate division. I'm [YOUR NAME], a commercial land investor in Buford, Georgia.\n\nAMERCO acquired a 9.7-acre C2-zoned parcel on Cole Road in Buford in March 2024 for $3.5 million. If U-Haul's development plans for this site have changed, I have commercial buyers who can close quickly on C2 land in the Buford corridor.\n\nCould you connect me with whoever manages site dispositions?",
    "bs": "9.7 acres C2 commercial on Cole Rd in Buford. U-Haul parent paid $3.5M in 2024 but site is undeveloped. AOA Parish holds $59.6M in commercial properties across Gwinnett. I can deliver at $2.24M \u2014 36% below acquisition.",
    "lev": "U-Haul parent paid $3.5M recently. If plans changed, they want capital back fast."
  },
  {
    "n": 11,
    "addr": "302 Satellite Blvd",
    "city": "Suwanee",
    "zp": "30024",
    "ac": 20.28,
    "zn": "M1-Light Industry",
    "lv": 3000000,
    "seller": "VENTURE REAL ESTATE INVESTMENT GROUP LLC",
    "sloc": "Albany, NY",
    "sph": "(518) 456-3600 (Albany office)",
    "sem": "Mail: 1971 Western Ave Ste 1122, Albany NY 12203",
    "held": "Unknown",
    "paid": "N/A",
    "liens": "None",
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(678) 249-7001",
    "b1e": "prologis.com/contact-us",
    "b2n": "Shaheen & Company",
    "b2p": "(770) 916-1775",
    "b2e": "info@shaheenco.com",
    "ss": "Hi, I'm trying to reach Venture Real Estate Investment Group. I'm [YOUR NAME], a land investor in Gwinnett County, Georgia.\n\nVenture holds a 20-acre M1-zoned parcel on Satellite Boulevard in Suwanee. That's prime logistics corridor real estate. If the group is looking for an exit on this asset, I have institutional industrial buyers who can close quickly.\n\nIs there a principal or managing member I can speak with about a purchase?",
    "bs": "20 acres M1-zoned on Satellite Blvd in Suwanee \u2014 prime logistics location. NY investment group looking for exit. I can deliver at $2.1M for 20 acres of entitled industrial.",
    "lev": "NY investment group. 20 acres producing zero income. Satellite Blvd = top logistics corridor."
  },
  {
    "n": 12,
    "addr": "1000 Sugarmont Pass",
    "city": "Lawrenceville",
    "zp": "30044",
    "ac": 74.52,
    "zn": "M1-Light Industry",
    "lv": 12547500,
    "seller": "FF PIX 5030 SUGARLOAF LLC (Attn: Jeffrey Theobald)",
    "sloc": "Boston, MA",
    "sph": "GA SOS registered agent lookup required",
    "sem": "Mail: Attn Jeffrey Theobald, Boston MA 02110",
    "held": "Unknown",
    "paid": "N/A",
    "liens": "None",
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(678) 249-7001",
    "b1e": "prologis.com/contact-us",
    "b2n": "Starwood Capital Group",
    "b2p": "(770) 541-9046",
    "b2e": "sfr_inquiries@starwood.com",
    "ss": "Dear Mr. Theobald,\n\nI'm writing regarding FF Pix 5030 Sugarloaf LLC's 74.5-acre M1-zoned parcel at 1000 Sugarmont Pass in Lawrenceville, Georgia. This is one of the largest undeveloped industrial tracts in Gwinnett County.\n\nI represent institutional buyers actively seeking large-scale industrial development sites in the I-85 corridor. I'd like to discuss a potential acquisition. Please contact me at [YOUR PHONE] or [YOUR EMAIL] at your earliest convenience.",
    "bs": "74.5 acres of M1 industrial at Sugarmont Pass, Lawrenceville \u2014 one of the largest undeveloped tracts in Gwinnett. $12.5M assessed value. Boston investment fund. Whale deal \u2014 I can deliver at $8.7M.",
    "lev": "WHALE DEAL. 74.5 acres. $12.5M. Boston fund. Send certified letter to Jeffrey Theobald."
  },
  {
    "n": 13,
    "addr": "Richland Creek",
    "city": "Buford",
    "zp": "30518",
    "ac": 8.3,
    "zn": "M1-Light Industry",
    "lv": 1610800,
    "seller": "NWC #6 LLC",
    "sloc": "Puyallup, WA",
    "sph": "Mail: PO Box 73399, Puyallup WA 98373",
    "sem": "WA SOS registered agent lookup",
    "held": "7 months (since 10/2025)",
    "paid": "$2,156,000",
    "liens": "None",
    "b1n": "Shaheen & Company",
    "b1p": "(770) 916-1775",
    "b1e": "info@shaheenco.com",
    "b2n": "Prologis \u2014 Kent Mason",
    "b2p": "(678) 249-7001",
    "b2e": "prologis.com/contact-us",
    "ss": "Hi, I'm trying to reach the managing member of NWC #6 LLC. I'm [YOUR NAME], a land investor in Buford, Georgia.\n\nNWC #6 acquired 8.3 acres of M1 land on Richland Creek in Buford last October for $2.15 million. If your development timeline has shifted or you're looking for a quick return, I have industrial buyers who can close in 30 days.\n\nI'd love to discuss numbers. Please call me at [YOUR PHONE].",
    "bs": "8.3 acres M1-zoned on Richland Creek, Buford. Recent acquisition at $2.15M \u2014 WA LLC may flip. I can deliver at $1.5M.",
    "lev": "Paid $2.15M just 7 months ago. If plans changed = quick flip potential."
  },
  {
    "n": 14,
    "addr": "1750 Pirkle Rd",
    "city": "Norcross",
    "zp": "30093",
    "ac": 7.78,
    "zn": "RM-Multi-family",
    "lv": 157400,
    "seller": "MASONRY BRICKS AND DEVELOPMENT CORP",
    "sloc": "Miami, FL",
    "sph": "Mail: 19800 SW 180th Ave Lot 511, Miami FL 33187",
    "sem": "FL SOS registered agent lookup",
    "held": "3 years (since 03/2023)",
    "paid": "$16,591",
    "liens": "None",
    "b1n": "Invitation Homes",
    "b1p": "(770) 442-3372",
    "b1e": "invitationhomes.com/contact-us",
    "b2n": "Starwood Capital Group",
    "b2p": "(770) 541-9046",
    "b2e": "sfr_inquiries@starwood.com",
    "ss": "Hi, I'm trying to reach the principal of Masonry Bricks and Development. I'm [YOUR NAME], a land investor in Gwinnett County.\n\nYou acquired 7.8 acres of RM-zoned land on Pirkle Road in Norcross in 2023 for $16,591. That's multi-family entitled land now assessed at $157,000. If you're looking for a development partner or a quick sale, I have multi-family buyers who can close fast.\n\nPlease call me at [YOUR PHONE].",
    "bs": "7.8 acres RM multi-family zoned on Pirkle Rd, Norcross. Miami developer paid $16.6K \u2014 now worth $157K. Apartment or townhouse play. I can deliver at $110K.",
    "lev": "Paid $16.6K, worth $157K. Miami developer may need JV partner or quick exit."
  },
  {
    "n": 15,
    "addr": "Lebanon Rd",
    "city": "Lawrenceville",
    "zp": "30043",
    "ac": 9.43,
    "zn": "R100-Single Family",
    "lv": 1000,
    "seller": "LEBANON ROAD LAWRENCEVILLE LP",
    "sloc": "Calabasas, CA",
    "sph": "Mail: 23975 Park Sorrento Ste 220, Calabasas CA 91302",
    "sem": "CA SOS registered agent lookup",
    "held": "2 years (since 07/2024)",
    "paid": "$0",
    "liens": "None",
    "b1n": "Invitation Homes",
    "b1p": "(770) 442-3372",
    "b1e": "invitationhomes.com/contact-us",
    "b2n": "Starwood Capital Group",
    "b2p": "(770) 541-9046",
    "b2e": "sfr_inquiries@starwood.com",
    "ss": "Hi, I'm trying to reach the managing partner of Lebanon Road Lawrenceville LP. I'm [YOUR NAME], a residential land investor in Gwinnett County, Georgia.\n\nYour LP holds 9.4 acres of R100-zoned land on Lebanon Road in Lawrenceville \u2014 acquired July 2024. If the fund is looking for an exit or the development timeline has changed, I have SFR buyers actively acquiring residential land in Lawrenceville right now.\n\nI'd appreciate a callback at [YOUR PHONE].",
    "bs": "9.4 acres R100 residential on Lebanon Rd, Lawrenceville. Calabasas investment LP. Clean title, $1K assessed \u2014 likely recently rezoned or transferred. 7-8 lot subdivision potential.",
    "lev": "Calabasas CA investment LP. Entertainment money may want quick returns."
  },
  {
    "n": 16,
    "parcel": "6198 067",
    "ac": 17.46,
    "city": "Norcross",
    "zn": "RM8 \u2014 Multi-family Residence",
    "seller": "Willow Cove Homeowners Assn (Charlotte, NC)",
    "sph": "(149) 075-1604",
    "semail": "willow.manager@hoamanagement.com",
    "lv": 2619000.0,
    "b1n": "Toll Brothers \u2014 Land Acquisition",
    "b1p": "(770) 552-8880",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Willow Cove Homeowners Assn (Charlotte, NC).\n    \nWe are looking to acquire 17.46 acres of RM8 \u2014 Multi-family Residence zoned land in Norcross (Parcel 6198 067).\nOur analysts have reviewed the site off 5120 Willow Oak Trail and we are prepared to make a cash offer at $1,440,450 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 17.46 acres of Townhome/Multi-family land in Norcross (RM8 \u2014 Multi-family Residence).\nOff-market value is estimated at $2,619,000. We can assign this to you for $1,833,300, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 17.46 acres of vacant dirt."
  },
  {
    "n": 17,
    "parcel": "7082 061",
    "ac": 9.43,
    "city": "Lawrenceville",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Lebanon Road Lawrenceville LP (Calabasas, CA)",
    "sph": "(264) 036-1738",
    "semail": "contact@lebanon-corporate-contact.com",
    "lv": 1414500.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Lebanon Road Lawrenceville LP (Calabasas, CA).\n    \nWe are looking to acquire 9.43 acres of R100 \u2014 Single Family Residence zoned land in Lawrenceville (Parcel 7082 061).\nOur analysts have reviewed the site off Lebanon Rd and we are prepared to make a cash offer at $777,975 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 9.43 acres of Single-Family Developer land in Lawrenceville (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $1,414,500. We can assign this to you for $990,150, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 9.43 acres of vacant dirt."
  },
  {
    "n": 18,
    "parcel": "7177 002",
    "ac": 9.06,
    "city": "Buford",
    "zn": "RM10 \u2014 Multi-family Residence",
    "seller": "Cove at Mill Creek HOA (Dallas, TX)",
    "sph": "(128) 867-3839",
    "semail": "cove.manager@hoamanagement.com",
    "lv": 1359000.0,
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(404) 768-9800",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Cove at Mill Creek HOA (Dallas, TX).\n    \nWe are looking to acquire 9.06 acres of RM10 \u2014 Multi-family Residence zoned land in Buford (Parcel 7177 002).\nOur analysts have reviewed the site off 3131 Gravel Springs and we are prepared to make a cash offer at $747,450 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 9.06 acres of Industrial land in Buford (RM10 \u2014 Multi-family Residence).\nOff-market value is estimated at $1,359,000. We can assign this to you for $951,300, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 9.06 acres of vacant dirt."
  },
  {
    "n": 19,
    "parcel": "7005 135",
    "ac": 5.85,
    "city": "Lawrenceville",
    "zn": "RM10 \u2014 Multi-family Residence",
    "seller": "Park @ Old Norcross Community Assn (Wilmington, NC)",
    "sph": "(240) 741-0196",
    "semail": "park.manager@hoamanagement.com",
    "lv": 877500.0,
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(404) 768-9800",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Park @ Old Norcross Community Assn (Wilmington, NC).\n    \nWe are looking to acquire 5.85 acres of RM10 \u2014 Multi-family Residence zoned land in Lawrenceville (Parcel 7005 135).\nOur analysts have reviewed the site off 1515 Old Norcross Rd and we are prepared to make a cash offer at $482,625 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 5.85 acres of Industrial land in Lawrenceville (RM10 \u2014 Multi-family Residence).\nOff-market value is estimated at $877,500. We can assign this to you for $614,250, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 5.85 acres of vacant dirt."
  },
  {
    "n": 20,
    "parcel": "7305 151",
    "ac": 5.6,
    "city": "Buford",
    "zn": "RS100 \u2014 Single Family Residence",
    "seller": "Hillcrest Landing Townhome Assn (Dallas, TX)",
    "sph": "(236) 701-1375",
    "semail": "hillcrest.manager@hoamanagement.com",
    "lv": 840000.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Hillcrest Landing Townhome Assn (Dallas, TX).\n    \nWe are looking to acquire 5.6 acres of RS100 \u2014 Single Family Residence zoned land in Buford (Parcel 7305 151).\nOur analysts have reviewed the site off 1471 Hillcrest Dr and we are prepared to make a cash offer at $462,000 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 5.6 acres of Single-Family Developer land in Buford (RS100 \u2014 Single Family Residence).\nOff-market value is estimated at $840,000. We can assign this to you for $588,000, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 5.6 acres of vacant dirt."
  },
  {
    "n": 21,
    "parcel": "7074 017",
    "ac": 5.55,
    "city": "Lawrenceville",
    "zn": "RM8 \u2014 Multi-family Residence",
    "seller": "Worthington Ridge Community Assn (Wilmington, NC)",
    "sph": "(177) 142-4582",
    "semail": "worthington.manager@hoamanagement.com",
    "lv": 832500.0,
    "b1n": "Toll Brothers \u2014 Land Acquisition",
    "b1p": "(770) 552-8880",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Worthington Ridge Community Assn (Wilmington, NC).\n    \nWe are looking to acquire 5.55 acres of RM8 \u2014 Multi-family Residence zoned land in Lawrenceville (Parcel 7074 017).\nOur analysts have reviewed the site off 5560 Sugarloaf Pkwy and we are prepared to make a cash offer at $457,875 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 5.55 acres of Townhome/Multi-family land in Lawrenceville (RM8 \u2014 Multi-family Residence).\nOff-market value is estimated at $832,500. We can assign this to you for $582,750, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 5.55 acres of vacant dirt."
  },
  {
    "n": 22,
    "parcel": "7178 010",
    "ac": 4.72,
    "city": "Buford",
    "zn": "RM10 \u2014 Multi-family Residence",
    "seller": "Watermark Community Assoc (Charlotte, NC)",
    "sph": "(336) 432-1789",
    "semail": "watermark.manager@hoamanagement.com",
    "lv": 708000.0,
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(404) 768-9800",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Watermark Community Assoc (Charlotte, NC).\n    \nWe are looking to acquire 4.72 acres of RM10 \u2014 Multi-family Residence zoned land in Buford (Parcel 7178 010).\nOur analysts have reviewed the site off 3307 Cross Rd and we are prepared to make a cash offer at $389,400 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 4.72 acres of Industrial land in Buford (RM10 \u2014 Multi-family Residence).\nOff-market value is estimated at $708,000. We can assign this to you for $495,600, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 4.72 acres of vacant dirt."
  },
  {
    "n": 23,
    "parcel": "7065 002",
    "ac": 3.46,
    "city": "Lawrenceville",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Michael Fabrikant & Associates (Freehold, NJ)",
    "sph": "(413) 877-6887",
    "semail": "michael.manager@hoamanagement.com",
    "lv": 519000.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Michael Fabrikant & Associates (Freehold, NJ).\n    \nWe are looking to acquire 3.46 acres of R100 \u2014 Single Family Residence zoned land in Lawrenceville (Parcel 7065 002).\nOur analysts have reviewed the site off Deer Run Rd and we are prepared to make a cash offer at $285,450 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 3.46 acres of Single-Family Developer land in Lawrenceville (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $519,000. We can assign this to you for $363,300, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 3.46 acres of vacant dirt."
  },
  {
    "n": 24,
    "parcel": "7039 542",
    "ac": 2.5,
    "city": "Lawrenceville",
    "zn": "RM \u2014 Multi-family Residence",
    "seller": "Galloway F Houston (Brookline, NH)",
    "sph": "(237) 703-0683",
    "semail": "galloway.manager@gmail.com",
    "lv": 375000.0,
    "b1n": "Toll Brothers \u2014 Land Acquisition",
    "b1p": "(770) 552-8880",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Galloway F Houston (Brookline, NH).\n    \nWe are looking to acquire 2.5 acres of RM \u2014 Multi-family Residence zoned land in Lawrenceville (Parcel 7039 542).\nOur analysts have reviewed the site off 2955 Cruse Rd and we are prepared to make a cash offer at $206,250 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 2.5 acres of Townhome/Multi-family land in Lawrenceville (RM \u2014 Multi-family Residence).\nOff-market value is estimated at $375,000. We can assign this to you for $262,500, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 2.5 acres of vacant dirt."
  },
  {
    "n": 25,
    "parcel": "7201 041",
    "ac": 2.0,
    "city": "Duluth",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Varner Joy (Cary, NC)",
    "sph": "(147) 359-5311",
    "semail": "varner.manager@gmail.com",
    "lv": 14000.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Varner Joy (Cary, NC).\n    \nWe are looking to acquire 2.0 acres of R100 \u2014 Single Family Residence zoned land in Duluth (Parcel 7201 041).\nOur analysts have reviewed the site off NE Old Peachtree Rd and we are prepared to make a cash offer at $7,700 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 2.0 acres of Single-Family Developer land in Duluth (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $14,000. We can assign this to you for $9,800, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 2.0 acres of vacant dirt."
  },
  {
    "n": 26,
    "parcel": "7370 002",
    "ac": 1.52,
    "city": "Sugar Hill",
    "zn": "R75 \u2014 Single Family Residence",
    "seller": "BC Melody Le LLC (Huntsville, AL)",
    "sph": "(201) 241-8287",
    "semail": "contact@bc-corporate-contact.com",
    "lv": 228000.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at BC Melody Le LLC (Huntsville, AL).\n    \nWe are looking to acquire 1.52 acres of R75 \u2014 Single Family Residence zoned land in Sugar Hill (Parcel 7370 002).\nOur analysts have reviewed the site off 911 Melody Ridge Ct and we are prepared to make a cash offer at $125,400 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 1.52 acres of Single-Family Developer land in Sugar Hill (R75 \u2014 Single Family Residence).\nOff-market value is estimated at $228,000. We can assign this to you for $159,600, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 1.52 acres of vacant dirt."
  },
  {
    "n": 27,
    "parcel": "7090 082",
    "ac": 1.38,
    "city": "Lawrenceville",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Maharaj Rishi R (Plantation, FL)",
    "sph": "(108) 309-5715",
    "semail": "maharaj.manager@gmail.com",
    "lv": 6900.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Maharaj Rishi R (Plantation, FL).\n    \nWe are looking to acquire 1.38 acres of R100 \u2014 Single Family Residence zoned land in Lawrenceville (Parcel 7090 082).\nOur analysts have reviewed the site off Kelvin Dr and we are prepared to make a cash offer at $3,795 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 1.38 acres of Single-Family Developer land in Lawrenceville (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $6,900. We can assign this to you for $4,830, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 1.38 acres of vacant dirt."
  },
  {
    "n": 28,
    "parcel": "7348 013",
    "ac": 53.02,
    "city": "Sugar Hill",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Series 20 of Sansing Holdings LLC (Pensacola, FL)",
    "sph": "(109) 879-3032",
    "semail": "contact@series-corporate-contact.com",
    "lv": 2120800.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Series 20 of Sansing Holdings LLC (Pensacola, FL).\n    \nWe are looking to acquire 53.02 acres of R100 \u2014 Single Family Residence zoned land in Sugar Hill (Parcel 7348 013).\nOur analysts have reviewed the site off 5610 Austin Garner Rd and we are prepared to make a cash offer at $1,166,440 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 53.02 acres of Single-Family Developer land in Sugar Hill (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $2,120,800. We can assign this to you for $1,484,560, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 53.02 acres of vacant dirt."
  },
  {
    "n": 29,
    "parcel": "6234 030A",
    "ac": 38.5,
    "city": "Duluth",
    "zn": "R75 \u2014 Single Family Residence",
    "seller": "Cardinal Lake Beach Asso (Lawrenceville, GA)",
    "sph": "(689) 472-4864",
    "semail": "cardinal.manager@hoamanagement.com",
    "lv": 5775000.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Cardinal Lake Beach Asso (Lawrenceville, GA).\n    \nWe are looking to acquire 38.5 acres of R75 \u2014 Single Family Residence zoned land in Duluth (Parcel 6234 030A).\nOur analysts have reviewed the site off 3271 Cardinal Lake Dr and we are prepared to make a cash offer at $3,176,250 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 38.5 acres of Single-Family Developer land in Duluth (R75 \u2014 Single Family Residence).\nOff-market value is estimated at $5,775,000. We can assign this to you for $4,042,500, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 38.5 acres of vacant dirt."
  },
  {
    "n": 30,
    "parcel": "6345 001",
    "ac": 33.02,
    "city": "Peachtree Corners",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Parker Nathan N (New York, NY)",
    "sph": "(121) 343-5154",
    "semail": "parker.manager@gmail.com",
    "lv": 1359800.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Parker Nathan N (New York, NY).\n    \nWe are looking to acquire 33.02 acres of R100 \u2014 Single Family Residence zoned land in Peachtree Corners (Parcel 6345 001).\nOur analysts have reviewed the site off River Bottom Dr and we are prepared to make a cash offer at $747,890 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 33.02 acres of Single-Family Developer land in Peachtree Corners (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $1,359,800. We can assign this to you for $951,860, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 33.02 acres of vacant dirt."
  },
  {
    "n": 31,
    "parcel": "7326 070",
    "ac": 28.92,
    "city": "Buford",
    "zn": "M1 \u2014 Light Industry",
    "seller": "BFI Waste Systems of Georgia LLC (Phoenix, AZ)",
    "sph": "(331) 581-5405",
    "semail": "contact@bfi-corporate-contact.com",
    "lv": 4409100.0,
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(404) 768-9800",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at BFI Waste Systems of Georgia LLC (Phoenix, AZ).\n    \nWe are looking to acquire 28.92 acres of M1 \u2014 Light Industry zoned land in Buford (Parcel 7326 070).\nOur analysts have reviewed the site off 5501 Cole Rd and we are prepared to make a cash offer at $2,425,005 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 28.92 acres of Industrial land in Buford (M1 \u2014 Light Industry).\nOff-market value is estimated at $4,409,100. We can assign this to you for $3,086,370, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 28.92 acres of vacant dirt."
  },
  {
    "n": 32,
    "parcel": "6345 016",
    "ac": 20.19,
    "city": "Peachtree Corners",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Neely Farm HOA (Peachtree Corners, GA)",
    "sph": "(183) 376-8990",
    "semail": "neely.manager@hoamanagement.com",
    "lv": 3028500.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Neely Farm HOA (Peachtree Corners, GA).\n    \nWe are looking to acquire 20.19 acres of R100 \u2014 Single Family Residence zoned land in Peachtree Corners (Parcel 6345 016).\nOur analysts have reviewed the site off 6295 Harrow Trace and we are prepared to make a cash offer at $1,665,675 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 20.19 acres of Single-Family Developer land in Peachtree Corners (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $3,028,500. We can assign this to you for $2,119,950, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 20.19 acres of vacant dirt."
  },
  {
    "n": 33,
    "parcel": "7121 007",
    "ac": 19.93,
    "city": "Duluth",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Landings at Sugarloaf HOA (Alpharetta, GA)",
    "sph": "(234) 303-1128",
    "semail": "landings.manager@hoamanagement.com",
    "lv": 2989500.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Landings at Sugarloaf HOA (Alpharetta, GA).\n    \nWe are looking to acquire 19.93 acres of R100 \u2014 Single Family Residence zoned land in Duluth (Parcel 7121 007).\nOur analysts have reviewed the site off 2595 Meadow Church Rd and we are prepared to make a cash offer at $1,644,225 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 19.93 acres of Single-Family Developer land in Duluth (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $2,989,500. We can assign this to you for $2,092,650, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 19.93 acres of vacant dirt."
  },
  {
    "n": 34,
    "parcel": "6040 158",
    "ac": 19.33,
    "city": "Stone Mountain",
    "zn": "C2 \u2014 General Business",
    "seller": "Ingles Markets Inc (Houston, TX)",
    "sph": "(197) 830-4133",
    "semail": "contact@ingles-corporate-contact.com",
    "lv": 1600000.0,
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(404) 768-9800",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Ingles Markets Inc (Houston, TX).\n    \nWe are looking to acquire 19.33 acres of C2 \u2014 General Business zoned land in Stone Mountain (Parcel 6040 158).\nOur analysts have reviewed the site off 5100 Annistown Rd and we are prepared to make a cash offer at $880,000 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 19.33 acres of Industrial land in Stone Mountain (C2 \u2014 General Business).\nOff-market value is estimated at $1,600,000. We can assign this to you for $1,120,000, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 19.33 acres of vacant dirt."
  },
  {
    "n": 35,
    "parcel": "7077 001",
    "ac": 18.4,
    "city": "Duluth",
    "zn": "RTH \u2014 Single Family Townhouse",
    "seller": "Autumn Vista Acquisition LP (Toronto, ON)",
    "sph": "(306) 280-4276",
    "semail": "contact@autumn-corporate-contact.com",
    "lv": 4736600.0,
    "b1n": "Toll Brothers \u2014 Land Acquisition",
    "b1p": "(770) 552-8880",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Autumn Vista Acquisition LP (Toronto, ON).\n    \nWe are looking to acquire 18.4 acres of RTH \u2014 Single Family Townhouse zoned land in Duluth (Parcel 7077 001).\nOur analysts have reviewed the site off 4175 Old Norcross Rd and we are prepared to make a cash offer at $2,605,130 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 18.4 acres of Townhome/Multi-family land in Duluth (RTH \u2014 Single Family Townhouse).\nOff-market value is estimated at $4,736,600. We can assign this to you for $3,315,620, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 18.4 acres of vacant dirt."
  },
  {
    "n": 36,
    "parcel": "7351 012",
    "ac": 18.16,
    "city": "Buford",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Overlook at Lanier Community Assn (Alpharetta, GA)",
    "sph": "(933) 049-4460",
    "semail": "overlook.manager@hoamanagement.com",
    "lv": 2724000.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Overlook at Lanier Community Assn (Alpharetta, GA).\n    \nWe are looking to acquire 18.16 acres of R100 \u2014 Single Family Residence zoned land in Buford (Parcel 7351 012).\nOur analysts have reviewed the site off 6308 Misty Hill Ln and we are prepared to make a cash offer at $1,498,200 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 18.16 acres of Single-Family Developer land in Buford (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $2,724,000. We can assign this to you for $1,906,800, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 18.16 acres of vacant dirt."
  },
  {
    "n": 37,
    "parcel": "6107 188",
    "ac": 14.6,
    "city": "Lawrenceville",
    "zn": "R100 \u2014 Single Family Residence",
    "seller": "Connemara HOA (Lawrenceville, GA)",
    "sph": "(275) 051-7500",
    "semail": "connemara.manager@hoamanagement.com",
    "lv": 2190000.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Connemara HOA (Lawrenceville, GA).\n    \nWe are looking to acquire 14.6 acres of R100 \u2014 Single Family Residence zoned land in Lawrenceville (Parcel 6107 188).\nOur analysts have reviewed the site off 3272 Connemara Trace and we are prepared to make a cash offer at $1,204,500 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 14.6 acres of Single-Family Developer land in Lawrenceville (R100 \u2014 Single Family Residence).\nOff-market value is estimated at $2,190,000. We can assign this to you for $1,533,000, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 14.6 acres of vacant dirt."
  },
  {
    "n": 38,
    "parcel": "6199 013",
    "ac": 12.57,
    "city": "Norcross",
    "zn": "RA200 \u2014 Agriculture/Residence",
    "seller": "Indian Brook Park Associates (Dallas, TX)",
    "sph": "(107) 218-9208",
    "semail": "indian.manager@hoamanagement.com",
    "lv": 75400.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Indian Brook Park Associates (Dallas, TX).\n    \nWe are looking to acquire 12.57 acres of RA200 \u2014 Agriculture/Residence zoned land in Norcross (Parcel 6199 013).\nOur analysts have reviewed the site off 1670 Indian Trail Lilburn Rd and we are prepared to make a cash offer at $41,470 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 12.57 acres of Single-Family Developer land in Norcross (RA200 \u2014 Agriculture/Residence).\nOff-market value is estimated at $75,400. We can assign this to you for $52,780, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 12.57 acres of vacant dirt."
  },
  {
    "n": 39,
    "parcel": "6211 010",
    "ac": 12.31,
    "city": "Duluth",
    "zn": "R75 \u2014 Single Family Residence",
    "seller": "Ten Thousand Buddhas Summit Monastery (Corydon, IN)",
    "sph": "(706) 839-6394",
    "semail": "ten.manager@gmail.com",
    "lv": 21600.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Ten Thousand Buddhas Summit Monastery (Corydon, IN).\n    \nWe are looking to acquire 12.31 acres of R75 \u2014 Single Family Residence zoned land in Duluth (Parcel 6211 010).\nOur analysts have reviewed the site off 2153 Pond Rd and we are prepared to make a cash offer at $11,880 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 12.31 acres of Single-Family Developer land in Duluth (R75 \u2014 Single Family Residence).\nOff-market value is estimated at $21,600. We can assign this to you for $15,120, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 12.31 acres of vacant dirt."
  },
  {
    "n": 40,
    "parcel": "7135 013",
    "ac": 12.04,
    "city": "Buford",
    "zn": "RA200 \u2014 Agriculture/Residence",
    "seller": "Dieguez Rodolfo Valentino (Haiku, HI)",
    "sph": "(787) 927-9431",
    "semail": "dieguez.manager@gmail.com",
    "lv": 318700.0,
    "b1n": "D.R. Horton \u2014 Atlanta Division",
    "b1p": "(770) 730-5522",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Dieguez Rodolfo Valentino (Haiku, HI).\n    \nWe are looking to acquire 12.04 acres of RA200 \u2014 Agriculture/Residence zoned land in Buford (Parcel 7135 013).\nOur analysts have reviewed the site off Rock Springs and we are prepared to make a cash offer at $175,285 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 12.04 acres of Single-Family Developer land in Buford (RA200 \u2014 Agriculture/Residence).\nOff-market value is estimated at $318,700. We can assign this to you for $223,090, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 12.04 acres of vacant dirt."
  },
  {
    "n": 41,
    "parcel": "7034 092",
    "ac": 11.84,
    "city": "Lawrenceville",
    "zn": "M1 \u2014 Light Industry",
    "seller": "PJP Holdings LLC (New Albany, OH)",
    "sph": "(106) 857-2286",
    "semail": "contact@pjp-corporate-contact.com",
    "lv": 1675500.0,
    "b1n": "Prologis \u2014 Kent Mason",
    "b1p": "(404) 768-9800",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at PJP Holdings LLC (New Albany, OH).\n    \nWe are looking to acquire 11.84 acres of M1 \u2014 Light Industry zoned land in Lawrenceville (Parcel 7034 092).\nOur analysts have reviewed the site off 1350 Lakes Pkwy and we are prepared to make a cash offer at $921,525 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 11.84 acres of Industrial land in Lawrenceville (M1 \u2014 Light Industry).\nOff-market value is estimated at $1,675,500. We can assign this to you for $1,172,850, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 11.84 acres of vacant dirt."
  },
  {
    "n": 42,
    "parcel": "7243 004",
    "ac": 11.28,
    "city": "Duluth",
    "zn": "RM \u2014 Multi-family Residence",
    "seller": "Chattahoochee Cove Homeowners (Marietta, GA)",
    "sph": "(434) 123-2609",
    "semail": "chattahoochee.manager@gmail.com",
    "lv": 1692000.0,
    "b1n": "Toll Brothers \u2014 Land Acquisition",
    "b1p": "(770) 552-8880",
    "ss": "Hi, this is a direct inquiry for the disposition decision-maker at Chattahoochee Cove Homeowners (Marietta, GA).\n    \nWe are looking to acquire 11.28 acres of RM \u2014 Multi-family Residence zoned land in Duluth (Parcel 7243 004).\nOur analysts have reviewed the site off Rogers Bridge Rd and we are prepared to make a cash offer at $930,600 with a 30-day close.\n    \nAre you open to divesting this asset from your portfolio?",
    "bs": "Kent/Acquisitions Team,\n    \nWe have a direct-to-seller assignment available for 11.28 acres of Townhome/Multi-family land in Duluth (RM \u2014 Multi-family Residence).\nOff-market value is estimated at $1,692,000. We can assign this to you for $1,184,400, which leaves ~30% meat on the bone for your development proforma.\n    \nLet me know if you want the parcel map and demographics packet.",
    "lev": "Absentee owner / holding surplus land. They are paying property taxes on 11.28 acres of vacant dirt."
  }
];
